version: "3.1"

services:
  app:
    build: .
    command: "pnpm start"
    restart: always
    depends_on:
      - redis
      - mongo
    networks:
      - app-network
    environment:
      TOKEN: ${TOKEN}
  redis:
    image: redis:alpine
    restart: always
    networks:
      - app-network
    ports:
      - 6379:6379
    expose:
      - 6379
    env_file:
      - .env
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
  mongo:
    image: mongo:latest
    restart: always
    networks:
      - app-network
    ports:
      - 27017:27017
    expose:
      - 27017
    env_file:
      - .env
    command: 
        - '--logpath'
        - '/var/log/mongodb/mongod.log'

networks:
  app-network:
    driver: bridge
